import { eq, tables, useDB } from '~~/layers/db/server/utils/db'

export default defineEventHandler(async (event) => {
  // Only allow in development
  if (process.env.NODE_ENV === 'production') {
    throw createError({
      statusCode: 403,
      statusMessage: 'Forbidden',
    })
  }

  const { email, hashedPassword, name, role } = await readBody(event)

  try {
    const db = useDB()

    // Check if user exists
    const existingUser = await db
      .select()
      .from(tables.users)
      .where(eq(tables.users.email, email))
      .get()

    if (existingUser) {
      // Update existing user with hashedPassword field
      await db.update(tables.users)
        .set({
          emailVerified: true,
          hashedPassword,
          name,
          role,
          updatedAt: new Date(),
        })
        .where(eq(tables.users.email, email))

      return { email, updated: true }
    }
    else {
      // Create new user (ID will be auto-generated by nanoid)
      await db.insert(tables.users)
        .values({
          createdAt: new Date(),
          email,
          emailVerified: true,
          hashedPassword,
          name,
          role,
          updatedAt: new Date(),
        })

      return { created: true, email }
    }
  }
  catch (error: any) {
    throw createError({
      statusCode: 500,
      statusMessage: error.message,
    })
  }
})
