#!/bin/bash

echo "🔧 Quick waitlist test setup"
echo ""
echo "To test the waitlist without sending real emails:"
echo ""
echo "1. Update your .env file:"
echo "   NUXT_PRIVATE_EMAIL_SEND_IN_DEV_MODE=false"
echo ""
echo "2. Restart your dev server"
echo ""
echo "3. Submit a NEW email address (not already in database)"
echo ""
echo "4. Check your terminal/console for the email content"
echo "   - You'll see 'Waitlist Confirmation' as the heading"
echo "   - The verification URL will show http://localhost:9009/..."
echo ""
echo "5. Copy the verification URL from console and open it in browser"
echo ""
echo "This way you can test the complete flow without email delivery issues!"