name: Preview Branch Deployment
on:
  push:
    branches:
      - preview
  workflow_dispatch:

jobs:
  deploy-preview:
    name: "Deploy Preview Branch"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    environment: staging
    env:
      NUXT_UI_PRO_LICENSE: ${{ secrets.NUXT_UI_PRO_LICENSE }}

    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Ensure NuxtHub module is installed
        run: pnpx nuxthub@latest ensure

      - name: Build project
        run: NUXT_UI_PRO_LICENSE=${{ secrets.NUXT_UI_PRO_LICENSE }} pnpm build
        
      - name: Deploy to NuxtHub
        uses: nuxt-hub/action@v2
        with:
          build: false
        env:
          NUXT_HUB_PROJECT_KEY: timezyme-revq